# Generated by Django 3.2.9 on 2023-08-30 06:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 30, 13, 48, 3, 800341), null=True)),
                ('write_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 30, 13, 48, 3, 800341), null=True)),
                ('name', models.CharField(max_length=100)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crmtag_created', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crmtag_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_tags',
            },
        ),
        migrations.CreateModel(
            name='CRMState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 30, 13, 48, 3, 800341), null=True)),
                ('write_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 30, 13, 48, 3, 800341), null=True)),
                ('name', models.CharField(max_length=100)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crmstate_created', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crmstate_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_state',
            },
        ),
        migrations.CreateModel(
            name='CRMLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 30, 13, 48, 3, 800341), null=True)),
                ('write_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 30, 13, 48, 3, 800341), null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('date_deadline', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crmlead_created', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.crmstate')),
                ('tags', models.ManyToManyField(blank=True, to='crm.CRMTag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crmlead_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_lead',
            },
        ),
        migrations.AddIndex(
            model_name='crmlead',
            index=models.Index(fields=['user'], name='crm_lead_user_id_e42c2d_idx'),
        ),
    ]
